{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b392f787",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "hello\n"
     ]
    }
   ],
   "source": [
    "print(\"hello\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4fafab1f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "PART 1: EXPLORATORY DATA ANALYSIS\n",
      "======================================================================\n",
      "       total_bill         tip        size     tip_pct\n",
      "count  244.000000  244.000000  244.000000  244.000000\n",
      "mean    19.785943    2.998279    2.569672   16.080258\n",
      "std      8.902412    1.383638    0.951100    6.107220\n",
      "min      3.070000    1.000000    1.000000    3.563814\n",
      "25%     13.347500    2.000000    2.000000   12.912736\n",
      "50%     17.795000    2.900000    2.000000   15.476977\n",
      "75%     24.127500    3.562500    3.000000   19.147549\n",
      "max     50.810000   10.000000    6.000000   71.034483\n",
      "\n",
      "--- Skewness & Kurtosis ---\n",
      "total_bill   skew=1.126  kurtosis=1.169\n",
      "tip          skew=1.456  kurtosis=3.550\n",
      "size         skew=1.439  kurtosis=1.672\n",
      "tip_pct      skew=3.329  kurtosis=26.554\n",
      "\n",
      "--- Correlation matrix ---\n",
      "            total_bill    tip   size  tip_pct\n",
      "total_bill       1.000  0.676  0.598   -0.339\n",
      "tip              0.676  1.000  0.489    0.342\n",
      "size             0.598  0.489  1.000   -0.143\n",
      "tip_pct         -0.339  0.342 -0.143    1.000\n",
      "\n",
      "======================================================================\n",
      "HYPOTHESIS TEST 1: Smokers vs Non-Smokers -> Tip % \n",
      "======================================================================\n",
      "Shapiro-Wilk (smokers):     p=5.9299e-11\n",
      "Shapiro-Wilk (non-smokers): p=3.0617e-01\n",
      "Levene's test: stat=14.7374, p=1.5781e-04\n",
      "Mann-Whitney U: stat=6709.5, p=5.6074e-01\n",
      "Welch t-test (reference): stat=0.4112, p=6.8166e-01\n",
      "Mean tip%, smokers=16.32  non-smokers=15.93\n",
      "Conclusion at alpha=0.05: Fail to Reject H0\n",
      "\n",
      "======================================================================\n",
      "HYPOTHESIS TEST 2: One-Way ANOVA -> Tip % across Days\n",
      "======================================================================\n",
      "Days: ['Sun', 'Sat', 'Thur', 'Fri']\n",
      "F-statistic=0.8480, p=4.6884e-01\n",
      "Conclusion at alpha=0.05: Fail to Reject H0\n",
      "\n",
      "--- Chi-Square (bonus): smoker vs day ---\n",
      "Chi2=25.7872, p=1.0568e-05, dof=3\n",
      "\n",
      "======================================================================\n",
      "PART 2: OLS REGRESSION MODEL (Dep. Var = tip)\n",
      "======================================================================\n",
      "                            OLS Regression Results                            \n",
      "==============================================================================\n",
      "Dep. Variable:                    tip   R-squared:                       0.470\n",
      "Model:                            OLS   Adj. R-squared:                  0.452\n",
      "Method:                 Least Squares   F-statistic:                     26.06\n",
      "Date:                Tue, 08 Sep 2026   Prob (F-statistic):           1.20e-28\n",
      "Time:                        10:14:07   Log-Likelihood:                -347.48\n",
      "No. Observations:                 244   AIC:                             713.0\n",
      "Df Residuals:                     235   BIC:                             744.4\n",
      "Df Model:                           8                                         \n",
      "Covariance Type:            nonrobust                                         \n",
      "==============================================================================\n",
      "                 coef    std err          t      P>|t|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------\n",
      "const          0.8719      0.421      2.071      0.039       0.042       1.702\n",
      "total_bill     0.0945      0.010      9.841      0.000       0.076       0.113\n",
      "size           0.1760      0.090      1.966      0.051      -0.000       0.352\n",
      "smoker_bin    -0.0864      0.147     -0.589      0.556      -0.375       0.202\n",
      "sex_bin       -0.0324      0.142     -0.229      0.819      -0.311       0.247\n",
      "time_bin      -0.0681      0.445     -0.153      0.878      -0.944       0.808\n",
      "day_Sat       -0.1215      0.310     -0.392      0.695      -0.732       0.489\n",
      "day_Sun       -0.0255      0.321     -0.079      0.937      -0.658       0.608\n",
      "day_Thur      -0.1623      0.393     -0.412      0.680      -0.937       0.613\n",
      "==============================================================================\n",
      "Omnibus:                       27.860   Durbin-Watson:                   2.096\n",
      "Prob(Omnibus):                  0.000   Jarque-Bera (JB):               52.555\n",
      "Skew:                           0.607   Prob(JB):                     3.87e-12\n",
      "Kurtosis:                       4.923   Cond. No.                         222.\n",
      "==============================================================================\n",
      "\n",
      "Notes:\n",
      "[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n",
      "\n",
      "--- Gauss-Markov Diagnostics ---\n",
      "Jarque-Bera: stat=52.5554, p=3.8703e-12\n",
      "Omnibus: stat=27.8598, p=8.9191e-07\n",
      "\n",
      "--- VIF (continuous predictors) ---\n",
      "const        VIF=1.000\n",
      "total_bill   VIF=1.558\n",
      "size         VIF=1.558\n",
      "\n",
      "Done.\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Lab-4 Analysis Script — Restaurant Tipping Behavior\n",
    "Part 1 (EDA + Hypothesis Testing) and Part 2 (OLS Modeling + Diagnostics)\n",
    "\"\"\"\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from scipy import stats\n",
    "import statsmodels.api as sm\n",
    "from statsmodels.stats.outliers_influence import variance_inflation_factor\n",
    "from statsmodels.stats.stattools import jarque_bera, omni_normtest\n",
    "\n",
    "df = pd.read_csv(\"data/tips.csv\")\n",
    "df[\"tip_pct\"] = df[\"tip\"] / df[\"total_bill\"] * 100  # tip percentage, the more meaningful metric\n",
    "\n",
    "print(\"=\" * 70)\n",
    "print(\"PART 1: EXPLORATORY DATA ANALYSIS\")\n",
    "print(\"=\" * 70)\n",
    "print(df.describe())\n",
    "\n",
    "print(\"\\n--- Skewness & Kurtosis ---\")\n",
    "for col in [\"total_bill\", \"tip\", \"size\", \"tip_pct\"]:\n",
    "    print(f\"{col:12s} skew={stats.skew(df[col]):.3f}  kurtosis={stats.kurtosis(df[col]):.3f}\")\n",
    "\n",
    "print(\"\\n--- Correlation matrix ---\")\n",
    "print(df[[\"total_bill\", \"tip\", \"size\", \"tip_pct\"]].corr().round(3))\n",
    "\n",
    "print(\"\\n\" + \"=\" * 70)\n",
    "print(\"HYPOTHESIS TEST 1: Smokers vs Non-Smokers -> Tip % \")\n",
    "print(\"=\" * 70)\n",
    "smokers = df.loc[df.smoker == \"Yes\", \"tip_pct\"]\n",
    "nonsmokers = df.loc[df.smoker == \"No\", \"tip_pct\"]\n",
    "\n",
    "sw_s = stats.shapiro(smokers)\n",
    "sw_ns = stats.shapiro(nonsmokers)\n",
    "print(f\"Shapiro-Wilk (smokers):     p={sw_s.pvalue:.4e}\")\n",
    "print(f\"Shapiro-Wilk (non-smokers): p={sw_ns.pvalue:.4e}\")\n",
    "\n",
    "lev = stats.levene(smokers, nonsmokers)\n",
    "print(f\"Levene's test: stat={lev.statistic:.4f}, p={lev.pvalue:.4e}\")\n",
    "\n",
    "mwu = stats.mannwhitneyu(smokers, nonsmokers, alternative=\"two-sided\")\n",
    "ttest = stats.ttest_ind(smokers, nonsmokers, equal_var=False)\n",
    "print(f\"Mann-Whitney U: stat={mwu.statistic:.1f}, p={mwu.pvalue:.4e}\")\n",
    "print(f\"Welch t-test (reference): stat={ttest.statistic:.4f}, p={ttest.pvalue:.4e}\")\n",
    "print(f\"Mean tip%, smokers={smokers.mean():.2f}  non-smokers={nonsmokers.mean():.2f}\")\n",
    "alpha = 0.05\n",
    "verdict = \"Reject H0\" if mwu.pvalue < alpha else \"Fail to Reject H0\"\n",
    "print(f\"Conclusion at alpha=0.05: {verdict}\")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 70)\n",
    "print(\"HYPOTHESIS TEST 2: One-Way ANOVA -> Tip % across Days\")\n",
    "print(\"=\" * 70)\n",
    "groups = [df.loc[df.day == d, \"tip_pct\"] for d in df.day.unique()]\n",
    "anova = stats.f_oneway(*groups)\n",
    "print(f\"Days: {list(df.day.unique())}\")\n",
    "print(f\"F-statistic={anova.statistic:.4f}, p={anova.pvalue:.4e}\")\n",
    "verdict2 = \"Reject H0\" if anova.pvalue < alpha else \"Fail to Reject H0\"\n",
    "print(f\"Conclusion at alpha=0.05: {verdict2}\")\n",
    "\n",
    "print(\"\\n--- Chi-Square (bonus): smoker vs day ---\")\n",
    "ct = pd.crosstab(df.smoker, df.day)\n",
    "chi2, chip, dof, exp = stats.chi2_contingency(ct)\n",
    "print(f\"Chi2={chi2:.4f}, p={chip:.4e}, dof={dof}\")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 70)\n",
    "print(\"PART 2: OLS REGRESSION MODEL (Dep. Var = tip)\")\n",
    "print(\"=\" * 70)\n",
    "\n",
    "m = df.copy()\n",
    "m[\"smoker_bin\"] = (m.smoker == \"Yes\").astype(int)\n",
    "m[\"sex_bin\"] = (m.sex == \"Male\").astype(int)\n",
    "m[\"time_bin\"] = (m.time == \"Dinner\").astype(int)\n",
    "m = pd.get_dummies(m, columns=[\"day\"], drop_first=True)\n",
    "day_cols = [c for c in m.columns if c.startswith(\"day_\")]\n",
    "\n",
    "feature_cols = [\"total_bill\", \"size\", \"smoker_bin\", \"sex_bin\", \"time_bin\"] + day_cols\n",
    "X = sm.add_constant(m[feature_cols].astype(float))\n",
    "y = m[\"tip\"].astype(float)\n",
    "\n",
    "ols_model = sm.OLS(y, X).fit()\n",
    "print(ols_model.summary())\n",
    "\n",
    "print(\"\\n--- Gauss-Markov Diagnostics ---\")\n",
    "resid = ols_model.resid\n",
    "jb_stat, jb_p, skew_r, kurt_r = jarque_bera(resid)\n",
    "print(f\"Jarque-Bera: stat={jb_stat:.4f}, p={jb_p:.4e}\")\n",
    "omni_stat, omni_p = omni_normtest(resid)\n",
    "print(f\"Omnibus: stat={omni_stat:.4f}, p={omni_p:.4e}\")\n",
    "\n",
    "print(\"\\n--- VIF (continuous predictors) ---\")\n",
    "vif_cols = [\"total_bill\", \"size\"]\n",
    "Xvif = sm.add_constant(m[vif_cols].astype(float))\n",
    "for i, col in enumerate([\"const\"] + vif_cols):\n",
    "    vif = variance_inflation_factor(Xvif.values, i)\n",
    "    print(f\"{col:12s} VIF={vif:.3f}\")\n",
    "\n",
    "print(\"\\nDone.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "43fa5439",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
